# Based on https://innerjoin.bit.io/automate-jupyter-notebooks-on-github-9d988ecf96a6
name: Update notebook slides

on:
  push

jobs:
  notebook_update:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: python -m pip install --upgrade pip -r requirements-dev.txt
      - name: Update analysis notebook
        run: |
          python -m pip install jupyter nbconvert nbformat
          jupyter nbconvert --to slides --execute notebook/index.ipynb --ExecutePreprocessor.kernel_name='python3' --SlidesExporter.reveal_transition='none' --template=nbconvert_template --TemplateExporter.extra_template_basedirs=notebook/ --output=index
          mv notebook/index.slides.html notebook/index.html
      - name: commit updated notebook
        uses: EndBug/add-and-commit@v7
        with:
          author_name: Plot update bot
          message: "Update Notebook slides"
          add: "notebook/index.html"